add more description

diff --git a/bin/generatetree b/bin/generatetree
--- a/bin/generatetree
+++ b/bin/generatetree
@@ -30,11 +30,12 @@ cd $root
 source $root/bin/environment.sh
 
 # Test for presence of required software
+echo "Checking for required software"
 error=""
 bcftools --help >/dev/null 2>&1 || (echo "could not load bcftools" >&2 && error="true")
 vcftools --help >/dev/null 2>&1 || (echo "could not load vcftools" >&2 && error="true")
 python --version >/dev/null 2>&1 || (echo "could not load Python 2.7" >&2 && error="true")
-#raxml -h >/dev/null 2>&1 || (echo "could not load raxml" >&2 && error="true")
+raxmlHPC-PTHREADS -h >/dev/null 2>&1 || (echo "could not load raxml" >&2 && error="true")
 # Tabix exits with error even if installed, so it needs a fancier test
 set +e #Temporarily disable strict error mode
 tabix -help >/dev/null 2>&1
@@ -64,6 +65,7 @@ fi
 # Once all of the cultivars are cleaned and split, the chromosomes can be merged by vcf-merge.
 # "bcftools merge" is supposed to be faster, but seems to have a problem with something in the format of these files.
 # The merge function includes filters to remove any sites that don't have at least one alternate allele and one match to the reference, as well as any "Multiple Nucleotide Polymorphism" sites.
+echo "Merging chromosomes"
 cd $split
 for chromosome in {chr01,chr02,chr03,chr04,chr05,chr06,chr07,chr08,chr09,chr10,chr11,chr12}; do
 	merge_chromosome $chromosome &
@@ -83,11 +85,11 @@ vcf-concat chr*.cleaned.vcf.gz > ${filename%.*}.merge.cleaned.vcf
 randomsubsetvcf ${filename%.*}.merge.cleaned.vcf 100000 > ../alignments/${filename%.*}.100000SNPs.vcf
 cd $alignments
 # Then the VCF is turned into a fasta file with a python script.
-echo "Python time"
+echo "Creating fasta file"
 python ../bin/snp2seq.py ${filename%.*}.100000SNPs.vcf
-echo "Python time over"
 
 cd $root
+echo "Generating alignment"
 fasta="${alignments}/${filename%.*}.100000SNPs.vcf.fasta"
 rm -f RAxML_${filename%.*}.ERROR
 rm -f RAxML_${filename%.*}.log
