testing

diff --git a/bin/generatetree b/bin/generatetree
--- a/bin/generatetree
+++ b/bin/generatetree
@@ -1,5 +1,5 @@
 #!/bin/bash
-set -euo pipefail
+
 ## This script takes as its input a file containing a list of 3Krice cultivars
 ## that have been input into the generatevcf script. This script merges the
 ## chromosomes in parallel, strips any sites that don't have SNPs, and
@@ -7,103 +7,143 @@ set -euo pipefail
 ## subset of these SNPs are chosen at random and used as an alignment from which
 ## a maximum-likelihood tree is generated.
 
-inputfile=$1
-filename=${inputfile##*/}
-cultivarlist=$(cat $inputfile)
+shopt -s extglob
 
-unction usage() {
+# help menu
+function usage() {
         echo "
                 Code4Rice3K Help Section:
                 =========================
 
-                Usage: $0 -f <cultivar> -r <path> -c <cpu_threads> -n <data_threads> -s <start_from_step> -t <stop_at_step> -o <run_only_step>
-                Example: $0 -f sample-1 -r pwd -c 12 -n 12
+                Usage: $0 -l <listofcultivars> -o <path> -m <mode> --nct <cpu_threads> --nt <data_threads>
+                Example: $0 -l mylist -o /usr/home/ -m pwd --nct 12 --nt 12
                 
-                Mandatory options:
-                -f <cultivar>           :       [string] the name of the chosen rice cultivar
-                -r <path>               :       [string] either "pwd" if run locally, or "hpc" if run on HPC computer
-                -c <cpu_threads>        :       [int] the number of CPU threads used by GATK (4-12 is recommended)
-                -n <data_threads>       :       [int] the number of data threads used by GATK (6-24 is recommended)
+                1) Mandatory options:
+                -l|--list <textfile>	       	 :       List containing the names of all cultivars to be inferred
+		-o|--outputdir <string>	         :	 Directory path for all output files
+                -m|--mode <string>               :       Either "pwd" if run locally, or "hpc" if run on HPC computer
 
-                * Optional setings:
-                -s <start_from_step>    :       [int] the number of the starting step, must be between 1-4 (see below) 
-                -t <stop_at_step>       :       [int] the number of the last step, must be between 1-4 (see below)
-                -o <run_only_step>      :       [int] the number of the step to run (see below)
+                2) Optional setings:
+		--nct <int>       		 :       The number of CPU threads used by GATK (4-12 is recommended)
+                --nt <int>      		 :       The number of data threads used by GATK (6-24 is recommended)
+                --startfromstep <string>   	 :       Indicate the starting step, must be between step1-step4 (see below) 
+                --stopatstep <string>      	 :       Indicate the last step, must be between step1-step4 (see below)
+                --runonlystep <string>     	 :       Indicate a single step to run, e.g. step1 or step3 (see below)
 
-                -h                      :       disply this help message
+                -h|--help                     	 :       Disply this help message
 
                 code4Rice3K workflow can be run entirely or only part of the workflow can run.
-                Below are the possible steps that can chosen for the "generatevcf" script:
+                Below are the possible steps that can chosen for the "generatetree" script:
 
-                step 1 downloading the .bam file
-                step 2 generating .gvcf file .bam, ATTN: To skip to this step, previous steps must have run successfully
-                step 3 generating .vcf file from .gvcf, ATTN: To skip to this step, previous steps must have run successfully
-                step 4 generate .vcf file for each chromosome, ATTN: To skip to this step, previous steps must have run successfully
+                step 1 merges each chromosome of every given cultivar 
+                step 2 generates VCF file for the merged chromosomes, ATTN: To skip to this step, previous steps must have run successfully
+                step 3 generates FASTA file, ATTN: To skip to this step, previous steps must have run successfully
+                step 4 generates alignment file, ATTN: To skip to this step, previous steps must have run successfully
         "
 }
 
 if [ -z "$*" ]; then usage ; exit 1 ; fi
 
-declare -a stepsToRun
-stepsToRun=(step1 step2 step3 step4)
-startFromStep=""
-stopAtStep=""
-runOnlyStep=""
+declare -a steps2run
+stepstorun=(step1 step2 step3 step4)
+startfromstep=""
+stopatstep=""
+runonlystep=""
 
-runStep1=0
-runStep2=0
-runStep3=0
-runStep4=0
+# Default option settings:
+outputdir="$pwd"
+configfile=""
 
-for step in ${stepsToRun[@]} ; do
-  if [[ $step == "step1" ]] ; then runStep1=1 ; fi
-  if [[ $step == "step2" ]] ; then runStep2=1 ; fi
-  if [[ $step == "step3" ]] ; then runStep3=1 ; fi
-  if [[ $step == "step4" ]] ; then runStep4=1 ; fi
-done
+OPTIONS=`getopt -o l:o:m:h --long list:,outputdir:,mode:,numproc:,numdata:,startfromstep,stopatstep:,runonlystep:,help -n 'code4Rice3K error' -- "$@"`
+if [ $? !+ 0 ] ; then echo " " ; echo "Could not parse options (see above) ..." >&2 ; usage ; exit 1 ; fi
 
-# Check if the user specified that this is a High Performance Computing environment
-while getopts "f:r:c:n:s:t:o:h" opt; do
-        case $opt in
-                f)
-                        cultivar=${OPTARG}
-                        echo "Processing ${cultivar}"
-                        ;;
-                r)
-                        if [[ $OPTARG == hpc ]]; then
-                                root="$PBS_O_WORKDIR"
-                                echo "root=$root"
-                                cd $root
-                                source $root/bin/environment.sh
-                                echo "Loading modules"
-                                . /etc/profile.d/modules.sh >/dev/null 2>&1
-                                module load samtools java tabix bcftools vcftools/0.1.13 python >/dev/null 2>&1
-                        elif [[ $OPTARG == pwd ]]; then
-                                root="$(pwd)"
-                                echo "root=$root"
-                                cd $root
-                                source $root/bin/environment.sh
-                        else
-                                echo "Need to specify path: pwd or hpc"
-                        fi
-                        ;;
-                c)
-                        nct=${OPTARG} ;;
-                n)
-                        nt=${OPTARG} ;;
-                s)
-                        startFromStep=${OPTARG} ;;
-                t)
-                        stopAtStep=${OPTARG} ;;
-                o)
-                        runOnlyStep=${OPTARG} ;;
-                h)
+eval set -- "$OPTIONS"
+
+while true ; do
+        case "$1" in
+                -l|--list)
+			case "$2" in
+				-*) echo "Please provide a valid list with cultivar names when using -l"; usage; exit 1 ;;
+				*) inputfile=$2 ; filename=${inputfile##*/} ; cultivarlist=$(cat $inputfile) ; shift 2 ;;
+			esac ;;
+
+		-o|--outputdir)
+			case "$2" in
+				-*) echo "Please designate an output path option when using -o"; usage; exit 1 ;;
+				*) outputdir=$2 ; shift ;;
+			esac ;;
+
+                -m|--mode)
+			case "$2" in
+				-*) echo "Please provide a valid mode option to -m"; usage; exit 1 ;; 
+                        	*) if [[ $2 == hpc ]]; then
+                                	root="$PBS_O_WORKDIR"
+                                	echo "root=$root"
+                                	cd $root
+                                	source $root/bin/environment.sh
+                                	echo "Loading modules"
+                                	. /etc/profile.d/modules.sh >/dev/null 2>&1
+                                	module load samtools java tabix bcftools vcftools/0.1.13 python >/dev/null 2>&1
+                        	elif [[ $2 == pwd ]]; then
+                                	root="$(pwd)"
+                                	echo "root=$root"
+                                	cd $root
+                                	source $root/bin/environment.sh
+                        	else
+                                	echo "Please provide a valid mode option to -m"; usage; exit 1
+                        	fi ;;
+			esac ;;
+
+                --nct)
+			case "$2" in
+				-*) echo "Please provide a valid integer for the number of cpu threads when using --nct"; usage; exit 1 ;;
+                        	*) nct=$2 ; shift 2 ;;
+			esac ;;
+
+                --nt)
+			case "$2" in 
+				-*) echo " please provide a valid integer for the number of data threads when using --nt"; usage; exit 1 ;;
+                        	*) nt=$2 ; shift 2 ;;
+			esac ;;
+
+                --startfromstep)
+			case "$2" in
+				-*) echo "Please designate the code4Rice3K step from which to start"; usage; exit 1 ;;
+                        	*) startfromstep=$2 ; shift 2 ;;
+			esac ;;
+
+                --stopatstep)
+			case "$2" in
+				-*) echo "Please designate the last code4Rice3K step to execute"; usage; exit 1 ;;
+				*) stopatstep=$2 ; shift 2 ;;
+			esac ;;
+
+                --runonlystep)
+			case "$2" in
+				-*) echo "Please designate the code4Rice3K step to execute"; usage; exit 1 ;;
+                        	*) runonlystep=$2 ; shift 2 ;;
+			esac ;;
+
+                h|--help)
                         usage; exit 1 ;;
+
+		--) shift ; break ;;
+
+		*) echo "Unknown option or error" ; usage; exit 1 ;;
         esac
 done
 
-cd $root
-source $root/bin/environment.sh
+runstep1=0
+runstep2=0
+runstep3=0
+runstep4=0
+
+for step in ${steps2run[@]} ; do
+  if [[ $step == "step1" ]] ; then runstep1=1 ; fi
+  if [[ $step == "step2" ]] ; then runstep2=1 ; fi
+  if [[ $step == "step3" ]] ; then runstep3=1 ; fi
+  if [[ $step == "step4" ]] ; then runstep4=1 ; fi
+done
 
 # Once all of the cultivars are cleaned and split, the chromosomes can be merged by vcf-merge.
 # "bcftools merge" is supposed to be faster, but seems to have a problem with something in the format of these files.
@@ -111,7 +151,7 @@ source $root/bin/environment.sh
 # as well as any "Multiple Nucleotide Polymorphism" sites.
 
 # Step 1
-if [[ runStep1 == 1 ]]; then
+if [[ runstep1 == 1 ]]; then
         echo ""
         echo "=============================================================================="
         echo "Step 1 Merging chromosomes ..."
@@ -126,7 +166,7 @@ fi
 wait
 
 # Step 2
-if [[ runStep2 == 1 ]]; then
+if [[ runstep2 == 1 ]]; then
         echo ""
         echo "=============================================================================="
         echo "Step 2 Assemble a VCF file containing all called SNPs ..."
@@ -144,7 +184,7 @@ if [[ runStep2 == 1 ]]; then
 fi
 
 # Step 3
-if [[ runStep3 == 1 ]]; then
+if [[ runstep3 == 1 ]]; then
         echo ""
         echo "=============================================================================="
         echo "Step 3 Generating FASTA file for alignment ..."
@@ -157,7 +197,7 @@ if [[ runStep3 == 1 ]]; then
 fi
 
 # Step 4
-if [[ runStep4 == 1 ]]; then
+if [[ runstep4 == 1 ]]; then
         echo ""
         echo "=============================================================================="
         echo "Step 4 Generating alignment ..."
@@ -185,3 +225,5 @@ fi
 #mpirun -n 6 raxmlHPC-MPI-AVX -f a -m ASC_GTRGAMMA --asc-corr=lewis -n ${fasta%%.vcf.fasta} -N 1000 -p 12345 -s ${fasta} -x 12345 2>&1 > RAxML_${fasta%%.vcf.fasta}.log || touch RAxML_${fasta%%.vcf.fasta}.ERROR
 
 echo "Finished"
+
+exit
