this should work now

diff --git a/bin/xcheckprerequisites b/bin/xcheckprerequisites
--- a/bin/xcheckprerequisites
+++ b/bin/xcheckprerequisites
@@ -1,10 +1,56 @@
 #!/bash/bin
 
-# This script will check for prerequisites:
+# This script will check for prerequisites for code4Rice3K:
 
-root="$(pwd)"
-cd $root
-source $root/bin/code4Rice3K.conf
+maindir="$(pwd)"
+
+function check_prereq() {
+        echo "Checking for required software"
+        error=""
+        samtools --help >/dev/null 2>&1 || (echo "could not find samtools, please install" >&2 && error="true")
+        bcftools --help >/dev/null 2>&1 || (echo "could not find bcftools, please install" >&2 && error="true")
+        vcftools --help >/dev/null 2>&1 || (echo "could not find vcftools, please install" >&2 && error="true")
+        java -version >/dev/null 2>&1 || (echo "could not find Java, please install" >&2 && error="true")
+        python --version >/dev/null 2>&1 || (echo "could not find Python 2.7, please install" >&2 && error="true")
+        raxmlHPC-PTHREADS -h >/dev/null 2>&1 || (echo "could not find raxml, please install" >&2 && error="true")
+        # Tabix exits with error even if installed, so it needs a fancier test
+        set +e #Temporarily disable strict error mode
+        tabix --help >/dev/null 2>&1
+        if [[ "$?" != "1" ]]; then #If tabix is not installed the error status should be 127
+                echo "could not find tabix, please install" >&2
+                error="true"
+        fi
+	echo "Softwares are installed"
+        set -e
+
+        # Check for biopython and pyvcf:
+        for module in vcf Bio; do
+                echo -n "Python module $module ... "
+                python -c "import $module" > /dev/null 2>&1
+                returnstatus=$?
+                if [ $returnstatus == "0" ]; then
+                        echo OK
+                else
+                    	echo "Please install biopython and pyvcf"
+                fi
+        done
+
+	if [[ -n "$error" ]]; then
+                echo "Please install required software" >&2
+                exit 1
+        fi
+
+        # check reference genome
+        if [[ ! -e ${reference}/IRGSP-1.0_genome.dict ]]; then
+                echo "Reference genome not found. You need to run setup.sh script" >&2
+                exit 1
+        fi
+
+	echo "System requirements are met"
+}
+
+cd $maindir
 
 check_prereq
 
+exit
